name: .NET CI Build

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ava.API
      uses: actions/checkout@v4
      with:
        path: ava.api
    - name: Checkout Ava.Shared
      uses: actions/checkout@v3
      with:
        repository: repasscloud/ava.shared
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ava.shared
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies (ava.shared)
      working-directory: ava.shared
      run: dotnet restore
    - name: Restore dependencies (ava.api)
      working-directory: ava.api
      run: dotnet restore
    - name: Checks
      run: pwd; ls; tree
      # - name: Build
    #   working-directory: ava.api
    #   run: dotnet build --configuration Release --no-restore
