name: .NET CI build merge

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ava.API
        uses: actions/checkout@v4
        with:
          path: Ava.Api

      - name: Checkout Ava.Shared
        uses: actions/checkout@v4
        with:
          repository: repasscloud/ava.shared
          token: ${{ secrets.GITHUB_TOKEN }}
          path: Ava.Shared

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies (ava.shared)
        working-directory: Ava.Shared
        run: dotnet restore

      - name: Restore dependencies (ava.api)
        working-directory: Ava.Api
        run: dotnet restore

      - name: Build
        working-directory: Ava.Api
        run: dotnet build --configuration Release --no-restore

  auto-pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: branch
        run: |
          echo "branch=$(echo $GITHUB_REF | sed 's#refs/heads/##')" >> $GITHUB_OUTPUT

      - name: Close any existing dev→main PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branchName="${{ steps.branch.outputs.branch }}"
          open_prs=$(gh pr list \
            --state open \
            --base main \
            --head "$branchName" \
            --json number \
            --jq '.[].number')
          if [ -n "$open_prs" ]; then
            for pr in $open_prs; do
              echo "Closing existing PR #$pr"
              gh pr close "$pr"
            done
          else
            echo "No open PRs to close"
          fi

      - name: Create Pull Request
        id: create_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branchName="${{ steps.branch.outputs.branch }}"
          PR_URL=$(gh pr create \
            --base main \
            --head "$branchName" \
            --title "chore: Auto PR $branchName into main" \
            --body "Automatically created by gh-actions.")
          PR_NUMBER=${PR_URL##*/}
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

  auto-merge:
    needs: auto-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge Dev→Main Pull Request (REST API)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr=$(gh pr list \
              --state open \
              --base main \
              --head dev \
              --limit 1 \
              --json number \
              --jq '.[0].number')

          if [ -z "$pr" ]; then
            echo "❌ No open PR found from dev to main—nothing to merge."
            exit 0
          fi

          echo "➡️ Merging PR #$pr via REST"
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/pulls/$pr/merge" \
            --input - <<<'{"merge_method":"merge"}'
